
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `R`=list(
        `type`="software", 
        `author`="R Core Team", 
        `year`=2018, 
        `title`="A Language and Envionment for Statistical Computing", 
        `publisher`="[Computer software]. Retrieved from https://cran.r-project.org/", 
        `url`="https://cran.r-project.org/"), 
    `TOSTER`=list(
        `type`="software", 
        `author`="Caldwell, A.R.", 
        `year`=2022, 
        `title`="TOSTER R package 0.5.1", 
        `publisher`="CRAN", 
        `url`="https://aaroncaldwell.us/TOSTERpkg/"))
